### ISSUE TITLE
RE: Intro chem - angstrom mention

### ISSUE THREAD

**Issue by xornand** [saylordotorg/text_introductory-chemistry#1]
Hey there

First of all, great job on this project. I don't want be a pedant, and I realize this is an _introduction_ to _chemistry_ and not a graduate level particle physics course, but when you bring up angstroms and then rationalize the unit as being 'The basic building block of all matter is the atom' . it's sort of, eh, misleading. I understand that you have to make some compromises when teaching concepts (i.e., no one mentions minkowski space, SR, or wave functions in standard newtonian physics 101), but the best textbooks I've read which elide details have a little footnote remarking on what is definitively known. 

Something in that case would be like -- "newtonian physics holds true for quite a lot of physics. it models everything you interact with in your daily life to with remarkable consistency. in fact, the 3 core newtonian laws remain consistent even on scales used in the calculations for sending rocketry to the moon! however, at the really small scale (see: "Quantum Mechanics"), as well as the really fast scale(see: Special Relativity), these laws start to break down."

No need for feynman diagrams or anything, but just a helpful historical note in a paragraph or 3 : 'since the mid 19th century, there were theoretical models that necessitated the existence of units smaller than the proton and neutron. [planck and the black body radiation historical note here]. in the 1925(might be wrong about this date), blah blah Dirac formalized modern quantum mechanics in theory. blah blah the 1960s experimental research, then maybe close it off with a mention of the 2012 higgs field experimentally confirmed and it's importance in the standard model as it's what _gives mass to everything_.

**Comment by saylordotorg-nobody** [comment]
Hi Andrew,

Thanks for your concern. Being mindful about the level of the material
we're presenting, while also not wanting to misrepresent ideas, is a
priority for us as well. We typically defer to our faculty members and
original content creators on questions like yours, but depending on how
comfortable you are with using Github, you can fork the repository, make
changes as you see fit, and submit a pull request for us to review and pull
into our version.

Thanks,

Nathan Thompson

## 

Nathan Thompson
Education Project Manager
_Saylor Academy http://www.saylor.org/_

_We're Bloggers. We Blog. We Blog Here http://www.saylor.org/blog/._

http://www.linkedin.com/company/the-saylor-foundation
http://www.facebook.com/saylorfoundation
https://plus.google.com/105426497265909285606/posts
http://www.twitter.com/saylordotorg
