### ISSUE TITLE
Electronegativity Chart problem

### ISSUE THREAD

**Issue by Qiangong2** [saylordotorg/text_introductory-chemistry#2]
On the electronegativity chart in section 13, as seen here: https://saylordotorg.github.io/text_introductory-chemistry/section_13/86495288d4baa241709baaed0454b93a.jpg

The symbol for Oxygen (O) is replaced by a (D).

**Comment by jazinheira** [comment]
Yep you are right. @athuggins Can we update/modify this textbook?

**Comment by athuggins** [comment]
Thanks for the heads-up; the image is fixed now.
